[foreword]
= முன்னுரை மற்றும் எச்சரிக்கை

எனக்கு சுமார் பதினான்கு அல்லது பதினைந்து வயதாக இருந்தபோது, பழங்கால
நூட்களில் விவரிக்கப்பட்டுள்ள சில உன்னதமான ஆரம்பகால தியான அனுபவங்களை
நான் தற்செயலாக சந்தித்தேன். அதன்பின் தயக்கத்துடனான ஆன்மீகத் தேடல்
என்னுள் தொடங்கியது. என்ன நடந்தது என்பதை நான் உணரவில்லை, திரும்பி 
வர முடியாத ஒரு புள்ளியை நான் கடந்துவிட்டேன் என்பதை நான் உணரவில்லை,
அதை நான் பின்னர் "எழுந்து கடந்து செல்லுதல்" (A&P) என்று அழைப்பேன்.
பிரகாசமான வெளிச்சத்துடன் மிகவும் விசித்திரமான கனவு நான் கண்டேன்.
என் முழு உடலும் இந்த உலகமும் ஆனந்தப்பெறுக்கில் வெடித்தது போல் தோன்றியது.
அதன்பின் என்னுள் ஒரு தேடல் எழுந்தது. நான் எதோ ஒன்றைக் கண்டுபிடிக்க
வேண்டும், ஆனால் அது என்னவென்று எனக்குத் தெரியவில்லை.

அப்போதிருந்து தியானப் பயிற்சிக்கு முற்றிலும் தொடர்பில்லாத பல்வேறு 
சூழ்நிலைகளில் A&P ஐத் தங்கள் வாழ்க்கையில் அனுபவித்து கடந்து வந்த ஏராளமான
நபர்களை நான் சந்தித்துள்ளேன். குறிப்பாக இது சிறப்பானதோ அல்லது 
அசாதாரணமானதோ அல்ல, மேலும் இது நிலையான மனித புலனுணர்வு 
வளர்ச்சியின் ஒரு பகுதியாக இப்போது நான் நினைக்கிறேன். இருப்பினும், அந்த 
நேரத்தில், நான் அதைப் பற்றி மிகக் குறைவாகவே சிந்தித்தேன், அதற்கான 
முறையான வார்த்தைகள், அதை வைப்பதற்கான சூழல் அல்லது அது என்ன 
என்பதைப் புரிந்து கொள்ளவில்லை. "என்ன செய்வது என்று எனக்குத் தெரியாத 
பிற வித்தியாசமான விஷயங்கள்" பற்றிய நினைவுகளுக்காக இது ஒரு மன 
கோப்புறையில் தாக்கல் செய்யப்பட்டது, இது இன்னும் பத்து ஆண்டுகளுக்கு எந்த 
அர்த்தமும் இல்லாத கோப்பு. பல ஆண்டுகளாக நான் வெறித்தனமாக தத்துவஞானம் 
பயின்றேன், இறுதியாக எந்த எண்ணமும் எனது ஆழ்ந்த ஆன்மீக சிக்கல்களைத் 
தீர்க்கப் போவதில்லை மற்றும் ஏற்கனவே தொடங்கிய பயிற்சியின் சுழற்சியை 
முடிக்கப் போவதில்லை என்பதை நான் உணரத் தொடங்கினேன்.
